### ISSUE TITLE
help: return token after user registration  (not only after login)

### ISSUE THREAD

**Issue by awebisam** [awebisam/The-Notes-Buddy-API#3]
let's implement authtoken returning with user register request.

**Comment by djzevenbergen** [comment]
It seems to be working

**Comment by ShubhamNagure** [comment]
I can help you!

**Comment by awebisam** [comment]
> I can help you!

I'd love that.

**Comment by n1rjal** [comment]
## Hello
@awebisam @ShubhamNagure @anushkarthik05 
I have implemented the requested feature.<br> Enjoy the web app
